version: '3.3'

services:
  app: &app
    build: .
    image: messi
    command: bash
    volumes:
      - '.:/app'
      - bundler-data:/usr/local/bundle/:cached
      - bin-data:/usr/local/bin/:cached
    environment:
      - REDIS_HOST=redis
      - RAILS_ENV=${RAILS_ENV:-development}
      - DATABASE_URL=postgres://postgres@db
    depends_on:
      - db
      - redis

  web:
    <<: *app
    build: .
    image: messi
    command: rails server
    ports:
      - "3000:3000"

  db:
    image: 'postgres:9.6'
    volumes:
      - pg-data:/var/lib/postgresql/data

  redis:
    image: redis:alpine

volumes:
  pg-data:
  bundler-data:
  bin-data:
